import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layouts/Header";
import { Orbitron, VT323, Audiowide, Silkscreen } from "next/font/google";
import Footer from "@/components/layouts/Footer";
import SideIndicator from "@/components/layouts/SideIndicator";

const orbitron = Orbitron({
  subsets: ["latin"],
  variable: "--font-orbitron",
});

const vt323 = VT323({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-vt323",
});

const audiowide = Audiowide({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-audiowide",
});

const silkscreen = Silkscreen({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-silkscreen",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${orbitron.variable} ${audiowide.variable} ${vt323.variable} ${silkscreen.variable} antialiased  relative w-full h-full m-0 p-0`}
      >
        <div className=" w-full h-full">
          <video
            className="fixed top-0 left-0 w-full h-full object-cover z-[-1] opacity-25"
            autoPlay
            loop
            muted
            playsInline
          >
            <source
              src="/video/3130182-hd_1920_1080_30fps.mp4"
              type="video/mp4"
            />
            Your browser does not support the video tag.
          </video>
          <div className="fixed top-0 left-0 w-full h-[100lvh] z-30 flex flex-col">
            <Header />
            <SideIndicator />
            <Footer />
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
